### ISSUE TITLE
Docstrings are unparsed as simple string values

### ISSUE THREAD

**Issue by gaborbernat** [simonpercivall/astunparse#13]
```python
# coding=utf-8
""" Test. """

import ast
import inspect

import astunparse


def x():
    """
    Test
    """
    pass


if __name__ == '__main__':
    p = ast.parse(inspect.getsource(x))
    r = astunparse.unparse(p)
    print(r)
```

becomes

```python
def x():
    '\n    Test\n    '
    pass
```

**Comment by simonpercivall** [comment]
Hi! I must have forgotten to reply. `astunparse` makes no effort to _exactly_ replicate the original source, and triple-quoted strings are functionally no different from regular strings.

**Comment by mskoh52** [comment]
Hi, just finding this issue now. Is there any reason not to use `ast.get_docstring` to check if the first item should be interpreted as a triple-quoted string?

**Comment by simonpercivall** [comment]
The biggest reason it hasn't been done: `astunparse` is meant to replicate as closely as possible what the `Tools/parser/unparse.py` code in the official Python source is doing.

If this would be a trivial PR, feel free to go ahead. However, the project has had several edge case bugs due to diffs vs. the source, so I'm generally wary of straying far.
